FIX: Primary key was without NONCLUSTERED for mssql server.
origam/origam-model pull request #8
Opened 2021-06-02 05:09 UTC by JiriPrajz

2021-06-02 05:20 UTC, washibana reviewed
I think, there should be a new version with deployment scripts fixing the situation instead of changing the existing ones. @tvavrda Do you agree?

2021-06-02 06:27 UTC, tvavrda commented
Yes, this fixes the new future projects but does not fix those already created.

2021-06-02 06:28 UTC, tvavrda requested changes
Has to be a change script. See the discussion.

2021-07-02 10:36 UTC, washibana approved these changes

2021-07-02 10:39 UTC, tvavrda approved these changes

2021-07-02 10:39 UTC, merged